version: 0.2
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
        - npm install --save react-router-dom
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
      - public/**/*
      - src/**/*
      - package.json-
      - appspec.yml
    name: BuildArtifact
    discard-paths: no
  cache:
    paths:
      - node_modules/**/*
