version: 0.2
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
        - npm install --save react-router-dom
    build:
      commands:
        - npm run build
  artifacts:
    type: zip
    files:
      - public/**/*
      - src/**/*
      - package.json
      - appspec.yml
  cache:
    paths:
      - node_modules/**/*
