version: 0.2
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
        - npm install --save react-router-dom
    build:
      commands:
        - npm run build
    post_build:
      commands:
        - echo Build completed on `date`
        - aws s3 cp --recursive --acl public-read ./build s3://<bucket-name>/
        - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/index.html s3://<bucket-name>/
  artifacts:
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
